name: Daily Instagram Auto Poster

on:
  schedule:
    - cron: '30 4 * * *'
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  run_poster:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install instaloader requests

      - name: Run Python Script
        env:
          # Yahan hum secrets pass kar rahe hain script ko
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          INSTAGRAM_USER: ${{ secrets.INSTAGRAM_USER }}
          INSTAGRAM_PASS: ${{ secrets.INSTAGRAM_PASS }}
        run: python main.py

      - name: Save History
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Check karega file hai ya nahi taaki error na aaye
          if [ -f video_queue.json ]; then
            git add video_queue.json
            git commit -m "Update posted video history" || echo "No changes to commit"
            git push
          else
            echo "History file not found, skipping save."
          fi
