name: Instagram Auto Poster

on:
  schedule:
    - cron: '0 */1 * * *'  # Ye har 1 ghante (1 hour) mein chalega
  workflow_dispatch:      # Isse aap "Run Workflow" button daba kar kabhi bhi chala sakte hain

jobs:
  run_bot:
    runs-on: ubuntu-latest
    
    # Ye permission zaroori hai taaki 'last_video.txt' save ho sake
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install instaloader requests python-telegram-bot

      - name: Run Python Script
        env:
          # Ye saare Secrets GitHub Settings se aayenge
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python main.py

      - name: Save & Update File
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add last_video.txt
          # Agar naya video mila to file save karke GitHub par upload karega
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update last video" && git push)
